apiVersion: v1
kind: Service
metadata:
  name: store-front
  namespace: petstore
  labels:
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app: store-front
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080